baseURL: "https://docs.corego.io/"
defaultContentLanguage: "en"
languageCode: "en-US"
title: "Corego Documentation"
theme: "learn"
copyright: "Corego"

languages:
  en:
    contentDir: content/en
    languageName: English
    weight: 10
    menu:

  zh-CN:
    contentDir: content/zh-CN
    languageName: 简体中文
    weight: 20
    menu:
      shortcuts:
        - name: "<i class='fab fa-fw fa-github'></i> GitHub"
          url: https://github.com/corego/corego
        - name: <i class='fas fa-fw fa-book'></i> GoDoc
          url: https://pkg.go.dev/github.com/corego/corego 
  
params:
  editURL: "https://github.com/corego/docs/edit/master/"
  description: "Documentation for Hugo Learn Theme"
  author: "Panlatent"

disqusShortname: corego
googleAnalytics: UA-174590674-1
